### PR TITLE
Split sqlg-postgres/h2/hsqldb to allow smaller artifacts

### PR DESCRIPTION
**Pull request by jotak**
New maven modules sqlg-postgres/h2/hsqldb-dialect are created without any dependency on gremlin-groovy
Old modules sqlg-postgres/h2/hsqldb now depend on them

It allows approx. 12MB gain when XXGremlinPlugin classes are not required.

See also issue #68

### CODE REVIEW

**Comment by jotak** [comment]
Maybe @metlos will also want to have a look at this

**Comment by jotak** [comment]
The build passes on my machine;
https://travis-ci.org/pietermartin/sqlg/builds/161637786#L1114
"Unknown host nexus.codehaus.org" => is it a network issue you commonly get?
https://support.sonatype.com/hc/en-us/articles/217611787-codehaus-org-Repositories-Should-Be-Removed-From-Your-Nexus-Instance

**Comment by pietermartin** [comment]
No I have not seen it, but travis sure has given me cause for pain before.

**Comment by jotak** [comment]
Thanks!

**Comment by pietermartin** [comment]
Thanks for the PR.
Not sure how your tests were passing.
I got some failures. Trivial failures as I hardcoded the path to tinkerpop-modern.kryo so the file could not be found with the new structure.
Changed that and `HsqldbAllTestl`, `SqlgHsqldbStructureStandardTest` and `SqlgHsqldbProcessStandardTest` tests passed.
Let see if travis is happier as it will run the Postgresql test which are somewhat slower.

**Comment by jotak** [comment]
Hi Pieter, I'm sorry for the test issues. The tests were taking ages on my PC and I run them in several shots, not altogether. I may have missed some. Hope it's all good now.

**Comment by pietermartin** [comment]
Yeah the mvn clean install runs the postgres tests which take long.
I generally run the Hsqldb tests which are orders of magnitude faster. Few minutes for all 3 test suites.
Unfortunately H2 is also slow even though the individual benchmark is faster than Hsqldb. Still need to investigate that. Slow startup and shutdown probably.

**Pull request merged**
