### PR TITLE
Unique constraints

### PR DESCRIPTION
**Pull request by metlos**
Add support for unique constraints on vertex properties.
A property can either be unique across any and all (current or future) vertex labels or it can be required to be unique amongst vertices of one or more labels. A single property can have several unique constraints meaning that it can be part of different sets of vertex labels that require the property to be unique amongst them.

Note that this is not completely finished, because some of the below items are not implemented. I'm putting the PR forward though so that you can review what I've done so far...
- [x] handle normal mode
- [ ] handle batch mode
- [ ] handle streaming mode

### CODE REVIEW

**Comment by pietermartin** [comment]
Thanks for the PR.
I added you as a collaborator to sqlg.

Can you perhaps put this PR on a branch? 

I am hesitant to merge this in right now. 

1) To first release sqlg in sync with TinkerPop 3.2.2
2) Would like to first complete the current #58 refactor before merging in your PR.

As #58 is precisely about the meta data management it will conflict somewhat with what you have done.
I added some comments on the issue to indicate my current thoughts.

However #58 will take me quite a while to complete. If you are anxious to get this PR included then I can merge it in first after releasing and then continue with #58

**Comment by metlos** [comment]
Thanks for granting me the commit access!

I'm using Sqlg through https://github.com/l2x6/srcdeps so I don't actually need a formal release to use the new code as long as it's in your repo (no matter the branch), which it now is, so I think we can move forward as you outlined.

**Comment by pietermartin** [comment]
I created #67 to discuss some ideas including unique constraints. Please have a look.

**Comment by pietermartin** [comment]
I noticed that you are not logging the sql being executed. Every sql statement should be logged.
```
        if (logger.isDebugEnabled()) {
            logger.debug(sql.toString());
        }
```
In log4j.properties `log4j.logger.org.umlg.sqlg=debug` will turn on logging.
It can be very noisy but indispensable for knowing if a gremlin query is optimized or not. Its a easy way to see how many sql statements one gremlin results in.

**Comment by pietermartin** [comment]
@metlos Have you had a chance to look at how it works now on master?

**Comment by pietermartin** [comment]
This is done for now with GlobalUniqueIndex support

**Pull request closed without merging**
