### PR TITLE
Allow bulk edge creation to include addition key/value pairs

### PR DESCRIPTION
**Pull request by jgustie**
I took a pass at #300 (rather then just constantly opening tickets, right? ;) ). I couldn't get local builds running so I don't know for sure if the test works or not. I tried sticking to style but I never know what Eclipse is doing so feel free to suggest changes if necessary.

### CODE REVIEW

**Comment by pietermartin** [comment]
Thanks for the PR, I'll have a look at it later.
Why can you not get the local build to work? Errors?

**Comment by jgustie** [comment]
There were compilation problems with the test project, it looked like it was unable to find Groovy. I didn't have Maven installed so I grabbed the latest (3.5.4). The test project also had problems in Eclipse, though I think that may have just been missing Groovy m2e extensions (aside from Gradle I don't have much experience with developing Groovy).

Also, I wasn't sure which databases I needed to have created: it would nice to have a Docker image that spins up the database ready for testing, I'm very busy right now, but I could put it on "the list" if I knew where to look for the expected initial state of Postgres.

**Comment by jgustie** [comment]
Just discovered the `.travis.yml`, that should have everything I need, let me give it a try...

**Comment by pietermartin** [comment]
I could not get Travis to work for Sqlg. The environment is too complex for Travis and needs too much memory.
Using Teamcity now running on
http://154.65.43.238:8111/viewType.html?buildTypeId=sqlg_Sqlg&guest=1

Not sure why your project did not build. `mvn clean install -DskipTests` is suppose to work.

Under the `sqlg-test` there is a file `tp3.databases` that indicates all the TinkerPop databases needed.
For Sqlg's own tests it is just `sqlgraphdb`

To run the full test suite is too intense. Need all the supported databases and it takes forever.
I'd suggest jut running `PostgresAnyTest` to test your PR specifically and `PostgresAllTest` to check something else did not break.

And ideally run `SqlgPostgresStructureStandardTest` and `SqlgPostgresProcessStandardTest` also as it will run TinkerPop's test suite. For this you will need to create all the TinkerPop databases.

**Comment by pietermartin** [comment]
A tad busy with the day job, should get round to checking the PR on the weekend.

**Pull request merged**
