### PR TITLE
Close data source if sqlg graph fails to open

### PR DESCRIPTION
**Pull request by vermaharsh**
#322

### CODE REVIEW

**Comment by pietermartin** [comment]
Thanks for the PR, I'll have a look at it today.

**Comment by vermaharsh** [comment]
Hi @pietermartin. Thanks for taking in my change. Can you also create a release with the latest changes so that we can pull the new jar in our project?

**Comment by pietermartin** [comment]
@vermaharsh I have released Sqlg `2.0.1`

**Comment by vermaharsh** [comment]
Sweet. Thanks a bunch!

**Pull request merged**
