### PR TITLE
Initial support for SQL Server and MySQL

### PR DESCRIPTION
**Pull request by ktschmidt**
These changes are what we are currently using for testing Sqlg with MySQL and SQL Server.  The MySQL should probably be considered experimental as the lack of support for schemas has some limitations.

As part of doing these plugins, a few changes were needed to core code but we believe they don't affect any other plugins or functionality.

If it is not desired to pull the SQL Server and/or MySQL plugins into the main code base, that is ok, but we'd like to see the other changes incorporated so we can use 1.3.4 unchanged and not have to use our fork with the changes.

### CODE REVIEW

**Comment by pietermartin** [comment]
Thanks for the PR, I am reviewing it.

**Comment by pietermartin** [comment]
An update,
The PR are is looking good.
There are a few tests failing on Postgresql.
In particular `TestSchema.testmanySchemas`. The reason is the edge's schema is being used to create the edge indexes where it should be the out vertex's schema.

I am just trying to set up a SQL Server environment to be able to test all the rdbmses and to see why its not failing on other dbs.

**Comment by ktschmidt** [comment]
If there is something we can help with, let me know.

**Comment by pietermartin** [comment]
OK got sql server installed.
I added the jdbc driver to the pom. You mentioned you are using a OSGI environment so probably you do not need the maven dependency.```
        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
            <version>6.1.7.jre8-preview</version>
        </dependency>
```
Now it connects but immediately the test  immediately fails as the `SqlgUtil.dropDb()`
throws
```
java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near the keyword 'CASCADE'.
```
SQL Server does not support `CASCADE` so we'll have to first drop the edge tables and then the vertex tables.
However more importantly did you run all the tests and if so how did they manage to get pass the `CASCADE` issue?

**Comment by ktschmidt** [comment]
Pieter,

Yeah, we separately install the JDBC driver in our OSGi environment so
didn't need the dependency.

And I'm a bit embarrassed to say the testing we've done is limited to
running our application and we haven't run the built-in tests.  What
setup/config/instructions are there for running those?  Let me know that
and we can certainly do that and work through any issues that crop up.

Kevin

**Comment by pietermartin** [comment]
Ok ,well the tests are going to have to pass first.

Just run `MSSqlServerAnyTest` to run a single test class. You can specify which class in `AnyTest`
To run all the test run `MSSqlServerAllTest`
Then to get the it to be kinda official TinkerPop, it must pass `SqlgMSSqlServerStructureStandardTest` and `SqlgGraphMSSqlServerProcessStandardTest`

All together is over 2000 tests giving some confidence in the dialect.

**Comment by ktschmidt** [comment]
I have the tests running and saw the error.  Tracking down a solution.

**Comment by ktschmidt** [comment]
Pieter,

I've gotten past the CASCADE error, but now get the exception below on a
later test.  I do not get this when doing the test for PostgreSQL.  Is
there something that needs to be configured for the connection pool that I
might be missing?

Thanks,

Kevin

Exception in thread "Thread-2031" java.lang.AssertionError:
java.sql.SQLException: An SQLException was provoked by the following
failure: java.lang.InterruptedException

at org.junit.Assert.fail(Assert.java:88)

at org.umlg.sqlg.test.schema.TestMultiThread$3.run(TestMultiThread.java:151)

ERROR 2017-06-04 22:06:29,356 [Thread-1955]
org.umlg.sqlg.test.schema.TestMultiThread: failure

java.lang.RuntimeException: java.sql.SQLException: An SQLException was
provoked by the following failure: java.lang.InterruptedException

at org.umlg.sqlg.structure.SqlgTransaction.doOpen(SqlgTransaction.java:65)

at
org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.open(AbstractTransaction.java:95)

at
org.apache.tinkerpop.gremlin.structure.Transaction$READ_WRITE_BEHAVIOR$1.accept(Transaction.java:208)

at
org.apache.tinkerpop.gremlin.structure.Transaction$READ_WRITE_BEHAVIOR$1.accept(Transaction.java:205)

at
org.apache.tinkerpop.gremlin.structure.util.AbstractThreadLocalTransaction.doReadWrite(AbstractThreadLocalTransaction.java:92)

at
org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.readWrite(AbstractTransaction.java:146)

at org.umlg.sqlg.structure.SqlgGraph.addVertex(SqlgGraph.java:361)

at org.umlg.sqlg.test.schema.TestMultiThread$3.run(TestMultiThread.java:118)

Caused by: java.sql.SQLException: An SQLException was provoked by the
following failure: java.lang.InterruptedException

at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)

at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)

at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:74)

at
com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:692)

at
com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)

at org.umlg.sqlg.structure.SqlgGraph.getConnection(SqlgGraph.java:1250)

at org.umlg.sqlg.structure.SqlgTransaction.doOpen(SqlgTransaction.java:56)

... 7 more

Caused by: java.lang.InterruptedException

at java.lang.Object.wait(Native Method)

at
com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1418)

at
com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:606)

at
com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:526)

at
com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:756)

at
com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:683)

... 10 more

Exception in thread "Thread-1955" java.lang.AssertionError:
java.sql.SQLException: An SQLException was provoked by the following
failure: java.lang.InterruptedException

at org.junit.Assert.fail(Assert.java:88)

at org.umlg.sqlg.test.schema.TestMultiThread$3.run(TestMultiThread.java:151)

INFO  2017-06-04 22:06:32,902 [main] org.umlg.sqlg.test.BaseTest: Startup
time for test = 0:00:03.560

**Comment by pietermartin** [comment]
Try increasing the number of connections SQL Server accepts. Looks like the pool timed out on getting a connection. This test is very heavy on resources.

**Comment by ktschmidt** [comment]
Pieter,

I did have my database set to a very high number of connections, it turns
out the configured pool in the Sqlg code was set to just 100.  Raising that
got past that issue.

But now I'm running in to an issue on TestMultiThread with locking:

ERROR 2017-06-06 16:09:50,302 [Thread-1801]
org.umlg.sqlg.test.schema.TestMultiThread: failure
java.lang.RuntimeException: timeout lapsed to acquire lock schema creation.
at org.umlg.sqlg.structure.Topology.lock(Topology.java:377)
at
org.umlg.sqlg.structure.VertexLabel.ensurePropertiesExist(VertexLabel.java:275)
at org.umlg.sqlg.structure.Schema.ensureVertexColumnsExist(Schema.java:236)
at
org.umlg.sqlg.structure.Topology.ensureVertexLabelPropertiesExist(Topology.java:614)
at org.umlg.sqlg.structure.SqlgElement.property(SqlgElement.java:207)
at org.umlg.sqlg.structure.SqlgVertex.property(SqlgVertex.java:185)
at org.umlg.sqlg.test.schema.TestMultiThread$3.run(TestMultiThread.java:123)

What is there a dialect can/is doing to affect the acquisition of this
lock?  What do I need to be looking at to get past this?

Thanks,

Kevin

**Comment by pietermartin** [comment]
Does the test pass if you reduce the number of threads?
If you commit your code I can pull your branch and have a look.

There is nothing the dialect can do about the locking. The current timeout is hard coded to 100 seconds. We could make that configurable but its almost definitely not the problem.

We'll have to investigate on SQL Server whats going on. Maybe there is a dead lock happening?

**Comment by pietermartin** [comment]
I made some changes, mostly around the index name.
All postgres, hsqldb tests are passing.
I removed the MySql dialect as I am already quite far advanced with a MariaDb dialect.
I work on the mssqlserver dialect this weekend to see how far well the tests do on it.

**Comment by ktschmidt** [comment]
Pieter,

Apologies for the lack of response.  Been swamped with a number of things.

Thanks for merging, this will make our build easier as we can use your
sqlg-core instead of a modified one.  I'll update to the latest and try the
tests again and try reducing the threads.

I did fix one issue with mapping double to the wrong datatype I'll send a
pull request over for in a minute, otherwise I've made no changes from what
was sent earlier.

Kevin

**Comment by ktschmidt** [comment]
Where is the MariaDb dialect code?  Is it in a branch and not master?

**Comment by ktschmidt** [comment]
I found a spot in sqlg-core that "as index" was being used unquoted.  The
below change fixes it.

*--- a/sqlg-core/src/main/java/org/umlg/sqlg/sql/parse/SchemaTableTree.java*

*+++ b/sqlg-core/src/main/java/org/umlg/sqlg/sql/parse/SchemaTableTree.java*

@@ -518,7 +518,7 @@ public class SchemaTableTree {



                 //print the ID of the incoming element.

                 if (first && subQueryLinkedList.getFirst().stepType !=
STEP_TYPE.GRAPH_STEP) {

-                    result += "a1." +
sqlgGraph.getSqlDialect().maybeWrapInQoutes("index") + " as index,\n\r";

+                    result += "a1." +
sqlgGraph.getSqlDialect().maybeWrapInQoutes("index") + " as " +
sqlgGraph.getSqlDialect().maybeWrapInQoutes("index") + ",\n\r";

                 }

                 first = false;

**Comment by pietermartin** [comment]
Added the index quote wrap in master.
The mariadb code in the `cockroachdb` branch.
It does not yet pass the test so I have not merged it into master yet.
I started on a cockroachdb dialect, then realized that it is similar to MySql in that it does not support schemas so decided to do mariadb at the same time.

**Comment by ktschmidt** [comment]
Great, will take a look and try it out.  What is the general approach for
dealing with no schema support?

**Comment by pietermartin** [comment]
The approach is that a `database` is synonymous with `schema`. This is working well for both `cockroachdb` and `mariadb`.
So `create schema x;` becomes `create database x`. Both `mariadb` and `cockroachdb` support joining across `database` so it is equivalent to `postgresql`, `hsqldb`, `h2` and I think `mssqlserver` that can join across `schema`.

The `cockroachdb` branch is a tad broken at present but I hope to have it working by monday.

**Comment by ktschmidt** [comment]
Yeah, that is what we'd done with MySQL.  We let Sqlg create the
sqlg_schema and gui_schema databases and we just created our "graph"
database.  The challenge with that is one database server can't support two
different installs at the same time.

**Comment by ktschmidt** [comment]
What is your rough schedule for releasing 1.4.0?

**Comment by pietermartin** [comment]
Well sooner the better as we are running on master branch at my work.
Basically get mssqlserver and mariadb to pass the test and we can release.
There are no outstanding bug or features at present.

**Comment by ktschmidt** [comment]
Sooner would work for us too.  Right now we are using our modified 1.3 as I
think you only merge our sqlg-core changes into master?

**Comment by pietermartin** [comment]
master has had many updates since you forked. And I only ran the tests for Postgres/Hsqldb and H2. You'll have to test master on your system.
I'll start running the tests on mssqlserver and see how it goes.

**Comment by pietermartin** [comment]
Regarding "The challenge with that is one database server can't support two different installs at the same time" I don't think there is much we can do about it. MariaDB only has a 2 level name-space, database and table. If the user needs a 3 level name-space then mildly humbly I'd say they should use a different database. The idea of Sqlg prefixing tables as a name-spacing mechanism is a too invasive change for me to consider.

How easy is it to just start up another MariaDB running on a different port? That should solve the multiple graph problem in a way.

**Pull request merged**
